cache:
  manager:
    fallbackToNoOpCache: true
    caffeineCaches:
      - names: [ "userBySubjectId" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 5000
        enableRecordStats: false
        expireAfterWriteSeconds: 20
      - names: [ "supportiveMaterial" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 600
      - names: [ "Reference" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 600
      - names: [ "depositConfigById" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 600
      - names: [ "depositSourcesByTenant" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 600
      - names: [ "affiliation" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 5000
        enableRecordStats: false
        expireAfterWriteSeconds: 20
      - names: [ "dashboardStatisticsByUserId" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 20
      - names: [ "fileTransformerConfigById" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 600
      - names: [ "fileTransformerSourcesByTenant" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 600
      - names: [ "tokenExchangeKey" ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 60
      - names: [ tenantByCode ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 20
      - names: [ tenantById ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 20
      - names: [ userAllowedTenant ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 20
      - names: [ userTenantRoles ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteSeconds: 20
    mapCaches:
  userBySubjectId:
    name: userBySubjectId
    keyPattern: user_by_subject_$subject$:v0
  tenantByCode:
    name: tenantByCode
    keyPattern: tenant_by_code_$code$:v0
  tenantById:
    name: tenantById
    keyPattern: tenant_by_id_$tenantId$:v0
  userAllowedTenant:
    name: userAllowedTenant
    keyPattern: user_allowed_tenant$tenant_id$_$user_id$:v0
  userTenantRoles:
    name: userTenantRoles
    keyPattern: user_tenant_roles$tenant_id$_$user_id$:v0
  supportiveMaterial:
    name: supportiveMaterial
    keyPattern: supportive_material_$type$_$lang$:v0
  Reference:
    name: Reference
    keyPattern: reference_$type$_$criteria$:v0
  dashboardStatisticsByUserId:
    name: dashboardStatisticsByUserId
    keyPattern: dashboard_stats_by_usr_$key$:v0
  depositConfigById:
    name: depositConfigById
    keyPattern: deposit_config_by_id_$repositoryId$_$tenantCode$:v0
  depositSourcesByTenant:
    name: depositSourcesByTenant
    keyPattern: deposit_sources_by_tenant_$tenantCode$:v0
  fileTransformerConfigById:
    name: fileTransformerConfigById
    keyPattern: file_transformer_config_by_id_$transformerId$_$tenantCode$:v0
  fileTransformerSourcesByTenant:
    name: fileTransformerSourcesByTenant
    keyPattern: ile_transformer_sources_by_tenant_$tenantCode$:v0
  token-exchange-key:
    name: tokenExchangeKey
    keyPattern: resolve_$keyhash$:v0
  affiliation:
    name: affiliation
    keyPattern: affiliation_$entity$_$user$_$tenant$_$type$:v0