fieldSetExpander:
  mappings:
    - key: DescriptionEditorDescriptionTemplateForDescriptionLookupFields
      fields:
        - descriptionTemplate.id
        - descriptionTemplate.label
        - descriptionTemplate.version
        - descriptionTemplate.versionStatus
        - descriptionTemplate.groupId
        - descriptionTemplate.isActive
        - descriptionTemplate.definition.pages.id
        - descriptionTemplate.definition.pages.ordinal
        - descriptionTemplate.definition.pages.title
        - descriptionTemplate.definition.pages.sections.id
        - descriptionTemplate.definition.pages.sections.ordinal
        - descriptionTemplate.definition.pages.sections.title
        - descriptionTemplate.definition.pages.sections.description
        - descriptionTemplate.definition.pages.sections.sections
        - descriptionTemplate.definition.pages.sections.fieldSets.id
        - descriptionTemplate.definition.pages.sections.fieldSets.ordinal
        - descriptionTemplate.definition.pages.sections.fieldSets.title
        - descriptionTemplate.definition.pages.sections.fieldSets.description
        - descriptionTemplate.definition.pages.sections.fieldSets.extendedDescription
        - descriptionTemplate.definition.pages.sections.fieldSets.additionalInformation
        - descriptionTemplate.definition.pages.sections.fieldSets.hasCommentField
        - descriptionTemplate.definition.pages.sections.fieldSets.hasMultiplicity
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.min
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.max
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.placeholder
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.tableView
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.id
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.textValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.textListValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.dateValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.booleanValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.validations
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.target
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.textValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.textListValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.dateValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.booleanValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.label
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.fieldType
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.options.label
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.options.value
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.multipleSelect
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.type
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.maxFileSizeInMB
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.types.label
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.types.value
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.referenceType.id
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.referenceType.name
    - key: DescriptionEditorDescriptionTemplateLookupFields
      fields:
        - id
        - label
        - version
        - versionStatus
        - groupId
        - isActive
        - definition.pages.id
        - definition.pages.ordinal
        - definition.pages.title
        - definition.pages.sections.id
        - definition.pages.sections.ordinal
        - definition.pages.sections.title
        - definition.pages.sections.description
        - definition.pages.sections.sections
        - definition.pages.sections.fieldSets.id
        - definition.pages.sections.fieldSets.ordinal
        - definition.pages.sections.fieldSets.title
        - definition.pages.sections.fieldSets.description
        - definition.pages.sections.fieldSets.extendedDescription
        - definition.pages.sections.fieldSets.additionalInformation
        - definition.pages.sections.fieldSets.hasCommentField
        - definition.pages.sections.fieldSets.hasMultiplicity
        - definition.pages.sections.fieldSets.multiplicity.min
        - definition.pages.sections.fieldSets.multiplicity.max
        - definition.pages.sections.fieldSets.multiplicity.placeholder
        - definition.pages.sections.fieldSets.multiplicity.tableView
        - definition.pages.sections.fieldSets.fields.id
        - definition.pages.sections.fieldSets.fields.defaultValue.textValue
        - definition.pages.sections.fieldSets.fields.defaultValue.textListValue
        - definition.pages.sections.fieldSets.fields.defaultValue.dateValue
        - definition.pages.sections.fieldSets.fields.defaultValue.booleanValue
        - definition.pages.sections.fieldSets.fields.validations
        - definition.pages.sections.fieldSets.fields.visibilityRules.target
        - definition.pages.sections.fieldSets.fields.visibilityRules.textValue
        - definition.pages.sections.fieldSets.fields.visibilityRules.textListValue
        - definition.pages.sections.fieldSets.fields.visibilityRules.dateValue
        - definition.pages.sections.fieldSets.fields.visibilityRules.booleanValue
        - definition.pages.sections.fieldSets.fields.data.label
        - definition.pages.sections.fieldSets.fields.data.fieldType
        - definition.pages.sections.fieldSets.fields.data.options.label
        - definition.pages.sections.fieldSets.fields.data.options.value
        - definition.pages.sections.fieldSets.fields.data.multipleSelect
        - definition.pages.sections.fieldSets.fields.data.type
        - definition.pages.sections.fieldSets.fields.data.maxFileSizeInMB
        - definition.pages.sections.fieldSets.fields.data.types.label
        - definition.pages.sections.fieldSets.fields.data.types.value
        - definition.pages.sections.fieldSets.fields.data.referenceType.id
        - definition.pages.sections.fieldSets.fields.data.referenceType.name