fieldSetExpander:
  mappings:
    - key: DescriptionEditorDescriptionTemplateForDescriptionLookupFields
      fields:
        - descriptionTemplate.id
        - descriptionTemplate.label
        - descriptionTemplate.version
        - descriptionTemplate.versionStatus
        - descriptionTemplate.groupId
        - descriptionTemplate.isActive
        - descriptionTemplate.definition.pages.id
        - descriptionTemplate.definition.pages.ordinal
        - descriptionTemplate.definition.pages.title
        - descriptionTemplate.definition.pages.sections.id
        - descriptionTemplate.definition.pages.sections.ordinal
        - descriptionTemplate.definition.pages.sections.title
        - descriptionTemplate.definition.pages.sections.description
        - descriptionTemplate.definition.pages.sections.sections
        - descriptionTemplate.definition.pages.sections.fieldSets.id
        - descriptionTemplate.definition.pages.sections.fieldSets.ordinal
        - descriptionTemplate.definition.pages.sections.fieldSets.title
        - descriptionTemplate.definition.pages.sections.fieldSets.description
        - descriptionTemplate.definition.pages.sections.fieldSets.extendedDescription
        - descriptionTemplate.definition.pages.sections.fieldSets.additionalInformation
        - descriptionTemplate.definition.pages.sections.fieldSets.hasCommentField
        - descriptionTemplate.definition.pages.sections.fieldSets.hasMultiplicity
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.min
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.max
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.placeholder
        - descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.tableView
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.id
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.textValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.textListValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.dateValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.booleanValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.validations
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.target
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.textValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.textListValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.dateValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.booleanValue
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.label
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.fieldType
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.options.label
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.options.value
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.multipleSelect
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.type
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.maxFileSizeInMB
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.types.label
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.types.value
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.referenceType.id
        - descriptionTemplate.definition.pages.sections.fieldSets.fields.data.referenceType.name
    - key: DescriptionEditorDescriptionTemplateLookupFields
      fields:
        - id
        - label
        - version
        - versionStatus
        - groupId
        - isActive
        - definition.pages.id
        - definition.pages.ordinal
        - definition.pages.title
        - definition.pages.sections.id
        - definition.pages.sections.ordinal
        - definition.pages.sections.title
        - definition.pages.sections.description
        - definition.pages.sections.sections
        - definition.pages.sections.fieldSets.id
        - definition.pages.sections.fieldSets.ordinal
        - definition.pages.sections.fieldSets.title
        - definition.pages.sections.fieldSets.description
        - definition.pages.sections.fieldSets.extendedDescription
        - definition.pages.sections.fieldSets.additionalInformation
        - definition.pages.sections.fieldSets.hasCommentField
        - definition.pages.sections.fieldSets.hasMultiplicity
        - definition.pages.sections.fieldSets.multiplicity.min
        - definition.pages.sections.fieldSets.multiplicity.max
        - definition.pages.sections.fieldSets.multiplicity.placeholder
        - definition.pages.sections.fieldSets.multiplicity.tableView
        - definition.pages.sections.fieldSets.fields.id
        - definition.pages.sections.fieldSets.fields.defaultValue.textValue
        - definition.pages.sections.fieldSets.fields.defaultValue.textListValue
        - definition.pages.sections.fieldSets.fields.defaultValue.dateValue
        - definition.pages.sections.fieldSets.fields.defaultValue.booleanValue
        - definition.pages.sections.fieldSets.fields.validations
        - definition.pages.sections.fieldSets.fields.visibilityRules.target
        - definition.pages.sections.fieldSets.fields.visibilityRules.textValue
        - definition.pages.sections.fieldSets.fields.visibilityRules.textListValue
        - definition.pages.sections.fieldSets.fields.visibilityRules.dateValue
        - definition.pages.sections.fieldSets.fields.visibilityRules.booleanValue
        - definition.pages.sections.fieldSets.fields.data.label
        - definition.pages.sections.fieldSets.fields.data.fieldType
        - definition.pages.sections.fieldSets.fields.data.options.label
        - definition.pages.sections.fieldSets.fields.data.options.value
        - definition.pages.sections.fieldSets.fields.data.multipleSelect
        - definition.pages.sections.fieldSets.fields.data.type
        - definition.pages.sections.fieldSets.fields.data.maxFileSizeInMB
        - definition.pages.sections.fieldSets.fields.data.types.label
        - definition.pages.sections.fieldSets.fields.data.types.value
        - definition.pages.sections.fieldSets.fields.data.referenceType.id
        - definition.pages.sections.fieldSets.fields.data.referenceType.name
    - key: PlanEditorDescriptionsLookupFields
      fields:
        - descriptions.id
        - descriptions.isActive
        - descriptions.createdAt
        - descriptions.updatedAt
        - descriptions.hash
        - descriptions.belongsToCurrentTenant
        - descriptions.id
        - descriptions.label
        - descriptions.description
        - descriptions.status.id
        - descriptions.status.name
        - descriptions.status.internalStatus
        - descriptions.availableStatuses.id
        - descriptions.availableStatuses.name
        - descriptions.availableStatuses.internalStatus
        - descriptions.availableStatuses.action
        - descriptions.status.definition.availableActions
        - descriptions.authorizationFlags.EditDescription
        - descriptions.authorizationFlags.DeleteDescription
        - descriptions.authorizationFlags.FinalizeDescription
        - descriptions.authorizationFlags.AnnotateDescription
        - descriptions.statusAuthorizationFlags.Edit
        - descriptions.planDescriptionTemplate.id
        - descriptions.planDescriptionTemplate.sectionId
        - descriptions.planDescriptionTemplate.isActive
        - descriptions.properties.fieldSets.comment
        - descriptions.properties.fieldSets.items.ordinal
        - descriptions.properties.fieldSets.items.fields.textValue
        - descriptions.properties.fieldSets.items.fields.textListValue
        - descriptions.properties.fieldSets.items.fields.dateValue
        - descriptions.properties.fieldSets.items.fields.booleanValue
        - descriptions.properties.fieldSets.items.fields.externalIdentifier.identifier
        - descriptions.properties.fieldSets.items.fields.externalIdentifier.type
        - descriptions.properties.fieldSets.items.fields.references.id
        - descriptions.properties.fieldSets.items.fields.references.label
        - descriptions.properties.fieldSets.items.fields.references.type.id
        - descriptions.properties.fieldSets.items.fields.references.type.name
        - descriptions.properties.fieldSets.items.fields.references.reference
        - descriptions.properties.fieldSets.items.fields.references.isActive
        - descriptions.properties.fieldSets.items.fields.tags.id
        - descriptions.properties.fieldSets.items.fields.tags.label
        - descriptions.properties.fieldSets.items.fields.tags.isActive
        - descriptions.properties.fieldSets.items.fields.tags.hash
        - descriptions.descriptionTags.id
        - descriptions.descriptionTags.tag.label
        - descriptions.descriptionTags.isActive
        - descriptions.descriptionReferences.data.fieldId
        - descriptions.descriptionReferences.data.ordinal
        - descriptions.descriptionReferences.reference.id
        - descriptions.descriptionReferences.reference.label
        - descriptions.descriptionReferences.reference.type.id
        - descriptions.descriptionReferences.reference.reference
        - descriptions.descriptionReferences.reference.source
        - descriptions.descriptionReferences.reference.sourceType
        - descriptions.descriptionReferences.isActive
        - descriptions.createdAt
        - descriptions.hash
        - descriptions.isActive
        - descriptions.availableStatuses.id
        - descriptions.availableStatuses.name
        - descriptions.availableStatuses.internalStatus
        - descriptions.availableStatuses.action
        - descriptions.descriptionTemplate.id
        - descriptions.descriptionTemplate.label
        - descriptions.descriptionTemplate.version
        - descriptions.descriptionTemplate.versionStatus
        - descriptions.descriptionTemplate.groupId
        - descriptions.descriptionTemplate.isActive
        - descriptions.descriptionTemplate.definition.pages.id
        - descriptions.descriptionTemplate.definition.pages.ordinal
        - descriptions.descriptionTemplate.definition.pages.title
        - descriptions.descriptionTemplate.definition.pages.sections.id
        - descriptions.descriptionTemplate.definition.pages.sections.ordinal
        - descriptions.descriptionTemplate.definition.pages.sections.title
        - descriptions.descriptionTemplate.definition.pages.sections.description
        - descriptions.descriptionTemplate.definition.pages.sections.sections
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.id
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.ordinal
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.title
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.description
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.extendedDescription
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.additionalInformation
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.hasCommentField
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.hasMultiplicity
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.min
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.max
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.placeholder
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.multiplicity.tableView
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.id
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.textValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.textListValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.dateValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.defaultValue.booleanValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.validations
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.target
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.textValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.textListValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.dateValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.visibilityRules.booleanValue
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.label
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.fieldType
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.options.label
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.options.value
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.multipleSelect
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.type
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.maxFileSizeInMB
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.types.label
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.types.value
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.referenceType.id
        - descriptions.descriptionTemplate.definition.pages.sections.fieldSets.fields.data.referenceType.name