kpi:
  user-indicator:
    id: 97c2d685-d7d2-4bd1-a287-ba329ad45d74
    label: test
    description: test
    url: url test
    code: test
    roles:
      - Admin
      - InstallationAdmin
    tenant-roles:
      - TenantAdmin