storage:
  task:
    enable: true
    intervalSeconds: 600
  service:
    defaultLanguage: en
    storages:
      - type: Temp
        basePath: ${FILE_STORAGE}/temp
      - type: Main
        basePath: ${FILE_STORAGE}/main
      - type: Transformer
        basePath: ${FILE_STORAGE}/transformer
      - type: Deposit
        basePath: ${FILE_STORAGE}/deposit
    tempStoreLifetimeSeconds: 7200
    material-files:
      localizedNameLanguageKey: "{lang}"

      userGuide: ${SUPPORTIVE_MATERIAL_USER_GUIDE_PATH:backend/web/src/main/resources/material/user-guide/}
      userGuideNamePattern: "UserGuide_{lang}.html"
      about: ${SUPPORTIVE_MATERIAL_ABOUT_PATH:backend/web/src/main/resources/material/about/}
      aboutNamePattern: "About_{lang}.html"
      termsOfService: ${SUPPORTIVE_MATERIAL_TERM_OF_SERVICE_PATH:backend/web/src/main/resources/material/terms-of-service/}
      termsOfServiceNamePattern: "TermsOfService_{lang}.html"
      glossary: ${SUPPORTIVE_MATERIAL_GLOSSARY_PATH:backend/web/src/main/resources/material/glossary/}
      glossaryNamePattern: "Glossary_{lang}.html"
      faq: ${SUPPORTIVE_MATERIAL_FAQ_PATH:backend/web/src/main/resources/material/faq/}
      faqNamePattern: "Faq_{lang}.html"
      language: ${SUPPORTIVE_MATERIAL_LANGUAGE_PATH:frontend/src/assets/i18n/}
      languageNamePattern: "{lang}.json"
      cookiePolicy: ${SUPPORTIVE_MATERIAL_COOKIE_POLICY_PATH:backend/web/src/main/resources/material/cookie-policy/}
      cookiePolicyNamePattern: "CookiePolicy_{lang}.html"
    static-files:
      semantics: ${SEMANTICS_PATH:backend/web/src/main/resources/Semantics.json}
