users:
  emailExpirationTimeSeconds:
    mergeAccountExpiration: ${MERGE_ACCOUNT_EXPIRATION:14400}
    removeCredentialExpiration: ${REMOVE_CREDENTIAL_EXPIRATION:14400}
    tenantSpecificInvitationExpiration: ${TENANT_SPECIFIC_INVITATION_EXPIRATION:2592000}
    planInvitationExternalUserExpiration: ${PLAN_INVITATION_EXTERNAL_USER_EXPIRATION:2592000}