package org.opencdmp.integrationevent.inbox.annotationstatusentitychanged;

import org.opencdmp.integrationevent.inbox.IntegrationEventHandler;

public interface AnnotationStatusEntityChangedIntegrationEventHandler extends IntegrationEventHandler {
}
