DO $$DECLARE
   this_version CONSTANT varchar := '01.00.009';
BEGIN
   PERFORM * FROM "DBVersion" WHERE version = this_version;
   IF FOUND THEN RETURN; END IF;

	UPDATE public."ReferenceType"
   SET definition='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><definition><fields><field code="pid" label="Pid Datasets" description="Pid Datasets" dataType="Text"/><field code="pidTypeField" label="PidTypeField Datasets" description="PidTypeField Datasets" dataType="Text"/></fields><sources><api><key>openaire</key><label>OpenAIRE</label><ordinal>1</ordinal><type>0</type><authentication><authUrlMethod>0</authUrlMethod><authUrlBody></authUrlBody><authTokenPath></authTokenPath><authUrl></authUrl><enabled>false</enabled><authType></authType></authentication><contentType>application/json; charset=utf-8</contentType><filterType>remote</filterType><firstPage>0</firstPage><requestHttpMethod>0</requestHttpMethod><paginationPath>$[''meta''][''pagination''][''page'',''pages'',''count'']</paginationPath><queries><query><cases><case><value>{like}</value></case></cases><defaultValue></defaultValue><name>like</name></query></queries><requestBody></requestBody><results><fieldsMapping><field><code>reference_id</code><responsePath>header.originalId.first()</responsePath></field><field><code>label</code><responsePath>result.maintitle</responsePath></field><field><code>description</code><responsePath>result.maintitle</responsePath></field><field><code>pid</code><responsePath>result.instance.first().pid.first().value</responsePath></field><field><code>pidTypeField</code><responsePath>result.instance.first().pid.first().typeCode</responsePath></field></fieldsMapping><resultsArrayPath>$[''results''][*]</resultsArrayPath></results><url>https://services.openaire.eu/search/v2/api/datasets/?q={like}&amp;page={page}&amp;size={pageSize}&amp;format=json</url></api></sources></definition>'
   WHERE id = 'a3ce0fb2-d72c-48bb-b322-7401940cb802';

   UPDATE public."ReferenceType"
   SET definition='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><definition><fields><field code="pid" label="pid" description="pid" dataType="Text"/><field code="pidTypeField" label="pidTypeField" description="pidTypeField" dataType="Text"/></fields><sources><api><key>openaire</key><label>OpenAIRE Publications</label><ordinal>1</ordinal><type>0</type><authentication><authUrlMethod>0</authUrlMethod><authUrlBody></authUrlBody><authTokenPath></authTokenPath><authUrl></authUrl><enabled>false</enabled><authType></authType></authentication><contentType>application/json;charset=UTF-8</contentType><filterType>remote</filterType><firstPage>0</firstPage><requestHttpMethod>0</requestHttpMethod><paginationPath>$[''meta''][''pagination''][''page'',''pages'',''count'']</paginationPath><queries><query><cases><case><value>{like}</value></case></cases><defaultValue>*</defaultValue><name>like</name></query></queries><requestBody></requestBody><results><fieldsMapping><field><code>reference_id</code><responsePath>header.originalId.first()</responsePath></field><field><code>label</code><responsePath>result.maintitle</responsePath></field><field><code>description</code><responsePath>result.maintitle</responsePath></field><field><code>pid</code><responsePath>result.instance.first().pid.first().value</responsePath></field><field><code>pidTypeField</code><responsePath>result.instance.first().pid.first().typeCode</responsePath></field></fieldsMapping><resultsArrayPath>$[''results''][*]</resultsArrayPath></results><url>https://services.openaire.eu/search/v2/api/resources?query=oaftype exact result and "{like}"&amp;page={page}&amp;size={pageSize}&amp;format=json</url></api></sources></definition>'
   WHERE id = '51225b6a-86a6-48ac-9192-f15096dbcb8a';

   UPDATE public."ReferenceType"
   SET definition='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><definition><fields><field code="pid" label="Pid Organisations" description="Pid Organisations" dataType="Text"/><field code="pidTypeField" label="PidType Organisations" description="PidType Organisations" dataType="Text"/></fields><sources><api><key>openaire</key><label>OpenAIRE</label><ordinal>1</ordinal><type>0</type><authentication><authUrlMethod>0</authUrlMethod><authUrlBody></authUrlBody><authTokenPath></authTokenPath><authUrl></authUrl><enabled>false</enabled><authType></authType></authentication><contentType>application/json; charset=utf-8</contentType><filterType>remote</filterType><firstPage>0</firstPage><requestHttpMethod>0</requestHttpMethod><paginationPath>$[''meta''][''pagination''][''page'',''pages'',''count'']</paginationPath><queries><query><cases><case><value>{like}</value></case></cases><defaultValue></defaultValue><name>like</name></query></queries><requestBody></requestBody><results><fieldsMapping><field><code>reference_id</code><responsePath>header.originalId.first()</responsePath></field><field><code>label</code><responsePath>organization.legalname</responsePath></field><field><code>description</code><responsePath>organization.legalname</responsePath></field><field><code>pid</code><responsePath>pid.first().value</responsePath></field><field><code>pidTypeField</code><responsePath>pid.first().typeCode</responsePath></field></fieldsMapping><resultsArrayPath>$[''results''][*]</resultsArrayPath></results><url>https://services.openaire.eu/search/v2/api/organizations/?q={like}&amp;page={page}&amp;size={pageSize}&amp;format=json</url></api></sources></definition>'
   WHERE id = '7eeffb98-58fb-4921-82ec-e27f32f8e738';

   UPDATE public."ReferenceType"
   SET definition='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><definition><sources><api><key>openaire</key><label>OpenAIRE</label><ordinal>1</ordinal><referenceTypeDependencyIds><referenceTypeDependencyIds>538928bb-c7c6-452e-b66d-08e539f5f082</referenceTypeDependencyIds></referenceTypeDependencyIds><type>0</type><authentication><authUrlMethod>0</authUrlMethod><authUrlBody></authUrlBody><authTokenPath></authTokenPath><authUrl></authUrl><enabled>false</enabled><authType></authType></authentication><contentType>application/json; charset=utf-8</contentType><filterType>remote</filterType><firstPage>0</firstPage><requestHttpMethod>0</requestHttpMethod><paginationPath>$[''meta''][''pagination''][''page'',''pages'',''count'']</paginationPath><queries><query><cases><case><value>{like}</value></case></cases><defaultValue>*</defaultValue><name>like</name></query><query><cases><case><referenceTypeId>538928bb-c7c6-452e-b66d-08e539f5f082</referenceTypeId><referenceTypeSourceKey>openaire</referenceTypeSourceKey><value>&amp;fq=(funder exact "{reference}")</value></case></cases><defaultValue></defaultValue><name>funderQuery</name></query></queries><requestBody></requestBody><results><fieldsMapping><field><code>reference_id</code><responsePath>header.originalId.first()</responsePath></field><field><code>label</code><responsePath>@{{project.title}} (@{{header.originalId[0]}})</responsePath></field><field><code>description</code><responsePath>project.title</responsePath></field></fieldsMapping><resultsArrayPath>$[''results''][*]</resultsArrayPath></results><url>https://services.openaire.eu/search/v2/api/resources?query=((oaftype exact project) and ((projectcode_nt exact "{like}")or("{like}"))){funderQuery}&amp;page={page}&amp;size={pageSize}&amp;format=json</url></api></sources></definition>'
   WHERE id = '5b9c284f-f041-4995-96cc-fad7ad13289c';

   INSERT INTO public."DBVersion" VALUES ('DMPDB', '01.00.009', '2025-05-28 12:00:00.000000+02', now(), 'Update datasets, publications, organizations and grants reference types');

END$$;